version: "3.5"

services:
  api01: &api
    build:
      context: .
    hostname: api01
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "30MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "3000:3000"

  nginxrinha:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "100MB"

#  db:
#    image: postgres:latest
#    hostname: db
#    environment:
#      - POSTGRES_PASSWORD=123
#      - POSTGRES_USER=admin
#      - POSTGRES_DB=rinha
#    ports:
#      - '5432:5432'
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
#    deploy:
#      resources:
#        limits:
#          cpus: '0.45'
#          memory: '140MB'

networks:
  default:
    driver: bridge
    name: rinha-nginx-rust-2024q1
